### ISSUE TITLE
Don't start puppet on boot, make sure it's not locked

### ISSUE THREAD

**Issue by njam** [cargomedia/vagrant-boxes#57]
When booting a new box:
```
# ps aux | grep puppet
root       641  1.9  1.2 218120 50612 ?        Ssl  17:24   0:00 /usr/bin/ruby /usr/bin/puppet agent
```

```
# ls -al /var/lib/puppet/state/agent_disabled.lock
-rw------- 1 root root 63 Oct 22 11:59 /var/lib/puppet/state/agent_disabled.lock
```

How about:
1. Install package
2. Stop daemon
3. Remove systemd entry (`/lib/systemd/system/puppet.service`? + reload?)
4. Remove agent lock file if present (`/var/lib/puppet/state/agent_disabled.lock`)?

**Comment by ppp0** [comment]
One needs to remove the old-school init script `/etc/init.d/puppet` as well otherwise `systemctl daemon-reload` will automagically migrate and create some generated service files for puppet (and start the service again)

When installing puppet (with puppet :smile: ), provide service script and file with the new define `service::define`

**Comment by njam** [comment]
Resolved with https://github.com/cargomedia/vagrant-boxes/pull/56
